version: "3.8"
services:
  # cloud_sql_proxy:
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
  #   command: /cloud_sql_proxy -instances=pl-web-219210:asia-east1:new-presslogic-uat=tcp:0.0.0.0:3306 -credential_file=/config -verbose
  #   ports: 
  #   - 3306:3306
  #   volumes: 
  #   - ./pl-web-219210-04537b65293f.json:/config
  #   container_name: cloud_sql_proxy
  proxysql-1:
    image: proxysql/proxysql:2.1.0
    volumes:
    - ./proxysql.cnf:/etc/proxysql.cnf
    ports:
    - 6032:6032
    - 6033:6033
    - 6070:6070
    networks:
    - proxysql
    container_name: proxysql-1
  proxysql-2:
    image: proxysql/proxysql:2.1.0
    volumes:
    - ./proxysql.cnf:/etc/proxysql.cnf
    ports:
    - 6032
    - 6033
    - 6070
    networks:
    - proxysql
    container_name: proxysql-2
  proxysql-3:
    image: proxysql/proxysql:2.1.0
    volumes:
    - ./proxysql.cnf:/etc/proxysql.cnf
    ports:
    - 6032
    - 6033
    - 6070
    networks:
    - proxysql
    container_name: proxysql-3
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
    - proxysql
    depends_on: 
    - proxysql-1
    - proxysql-2
    - proxysql-3
    container_name: mysql

networks: 
  proxysql:
    name: proxysql